// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nadasdladany.Data;

#nullable disable

namespace Nadasdladany.Migrations
{
    [DbContext(typeof(NadasdladanyDbContext))]
    partial class NadasdladanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nadasdladany.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FeaturedImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nádasdladány Önkormányzat",
                            CategoryId = 2,
                            Content = "<p>Részletes leírás az ünnepi megemlékezésről, amely a nemzeti ünnepünk alkalmából került megrendezésre a község főterén. Beszédet mondott Varga Tünde polgármester asszony.</p>",
                            Excerpt = "Rövid összefoglaló az ünnepi megemlékezésről, amely a főtéren került megrendezésre.",
                            FeaturedImageUrl = "/images/placeholder/news_placeholder_1.jpg",
                            IsPublished = true,
                            LastModifiedDate = new DateTime(2024, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            PublishedDate = new DateTime(2024, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "unnepi-megemlekezes-foteren",
                            Title = "Ünnepi Megemlékezés a Főtéren",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nádasdladány Önkormányzat",
                            CategoryId = 1,
                            Content = "<p>Az új játszótér átadásának részletei. Modern játékokkal és biztonságos környezettel várjuk a gyermekeket és családjaikat.</p>",
                            Excerpt = "Örömmel jelentjük be, hogy átadásra került a felújított központi játszótér a Kossuth utcában.",
                            FeaturedImageUrl = "/images/placeholder/news_placeholder_2.jpg",
                            IsPublished = true,
                            LastModifiedDate = new DateTime(2024, 4, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            PublishedDate = new DateTime(2024, 4, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "uj-jatszoter-atadasa-kossuth-utcaban",
                            Title = "Új Játszótér Átadása a Kossuth Utcában",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            Author = "Nádasdladány Önkormányzat",
                            CategoryId = 3,
                            Content = "<p>Tájékoztatjuk a tisztelt lakosságot, hogy a következő közmeghallgatás időpontja 2024. május 15., 17:00. Helyszín: Művelődési Ház. Témák: éves költségvetés, fejlesztési tervek.</p>",
                            Excerpt = "Fontos információk a következő közmeghallgatásról, melynek fő témái a költségvetés és a fejlesztések lesznek.",
                            IsPublished = true,
                            LastModifiedDate = new DateTime(2024, 5, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            PublishedDate = new DateTime(2024, 5, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "kozmeghallgatas-idopontja-temai",
                            Title = "Közmeghallgatás Időpontja és Témái",
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("Nadasdladany.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hírek a helyi önkormányzat működéséről.",
                            Name = "Önkormányzati Hírek",
                            Slug = "onkormanyzati-hirek"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Információk a település közösségi programjairól.",
                            Name = "Közösségi Események",
                            Slug = "kozossegi-esemenyek"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fontos közlemények a lakosság számára.",
                            Name = "Közlemények",
                            Slug = "kozlemenyek"
                        });
                });

            modelBuilder.Entity("Nadasdladany.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Organizer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Egész napos programok kicsiknek és nagyoknak. Koncertek, főzőverseny, kézműves vásár, gyerekprogramok és esti tűzijáték.",
                            EndDate = new DateTime(2024, 6, 16, 22, 0, 0, 0, DateTimeKind.Utc),
                            EventUrl = "/esemenyek/falunap-2024",
                            IsAllDay = false,
                            Location = "Községi Sportpálya és Szabadidőpark",
                            Organizer = "Nádasdladány Önkormányzat",
                            StartDate = new DateTime(2024, 6, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Nádasdladányi Falunap 2024"
                        },
                        new
                        {
                            Id = 2,
                            ContactInfo = "konyvtar@nadasdladany.hu",
                            Description = "Beszélgetés a nyár legnépszerűbb könyveiről, ajánlók és közös élmények megosztása.",
                            EndDate = new DateTime(2024, 6, 26, 18, 0, 0, 0, DateTimeKind.Utc),
                            IsAllDay = false,
                            Location = "Helyi Könyvtár Olvasóterme",
                            Organizer = "Nádasdladányi Könyvtár",
                            StartDate = new DateTime(2024, 6, 26, 17, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Könyvtári Olvasóklub: Nyári Olvasmányok"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Szeretettel várjuk szépkorú lakosainkat egy közös ünnepségre a Művelődési Ház nagytermében. Ünnepi műsorral és vendéglátással készülünk.",
                            IsAllDay = false,
                            Location = "Művelődési Ház",
                            Organizer = "Nádasdladány Önkormányzat és a Helyi Nyugdíjas Klub",
                            StartDate = new DateTime(2024, 7, 11, 15, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Idősek Napja Ünnepség"
                        });
                });

            modelBuilder.Entity("Nadasdladany.Models.Article", b =>
                {
                    b.HasOne("Nadasdladany.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Nadasdladany.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
